# Generated by Django 4.2.5 on 2023-09-14 14:21

from django.db import migrations, models
import django.db.models.deletion
import shop.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_game', models.CharField(max_length=255)),
                ('CPU', models.CharField(max_length=255)),
                ('video_card', models.CharField(max_length=255)),
                ('RAM', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=255, unique=True)),
                ('poster', models.ImageField(blank=True, upload_to=shop.models.get_path_and_name)),
                ('description', models.TextField()),
                ('language', models.CharField(choices=[('no_rus', 'Английский'), ('rus_sub', 'Русский (субтитры)'), ('rus_voice', 'Русский (озвучка)')], max_length=100)),
                ('year', models.PositiveSmallIntegerField()),
                ('developer', models.CharField(max_length=100)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=5)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('genre', models.ManyToManyField(related_name='product_genre', to='shop.genre')),
                ('requirement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.requirement')),
            ],
        ),
    ]
