# Generated by Django 4.2.5 on 2023-09-18 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='genre',
        ),
        migrations.AddField(
            model_name='genre',
            name='product',
            field=models.ManyToManyField(related_name='product_genre', to='shop.product'),
        ),
    ]
