# Generated by Django 4.2.5 on 2023-09-20 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_product_genre_genre_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='slug',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
